metadata:
  T2 Trainspotting (2017):
    match:
      title: T2 Trainspotting
      year: 2017
    title: T2 Trainspotting
    url_poster: https://theposterdb.com/api/assets/201516
    year: 2017
  Trainspotting (1996):
    match:
      title: Trainspotting
      year: 1996
    title: Trainspotting
    url_poster: https://theposterdb.com/api/assets/201515
    year: 1996
